name: Build

on:
  push:
    paths-ignore:
      - "docs/**"
      - "logo/**"
      - "examples/**"
      - "README.md"
    branches:
      - "master"

  pull_request:
    branches:
      - "master"
      - "feat/*"
      - "fix/*"

jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volesen/setup-skaffold@v1.1
        with:
          version: v1.38.0
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: "1.17.7"
      - run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
      - uses: extractions/setup-just@v1
      - run: just lint
      - run: just test
      - uses: rinx/setup-k3d@v0.0.4
        with:
          skipClusterCreation: true
      - run: just k3d
      - run: pip install httpie
      - run: just test-e2e-all
